// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"delivery-service/config"
	"delivery-service/internal/adapter/userserv"
	"delivery-service/internal/api"
	"delivery-service/internal/domain/repos"
	"delivery-service/internal/grpc-service/interceptor"
	"delivery-service/internal/grpc-service/protobuf/deliveryGrpc"
	"delivery-service/internal/middleware"
	"delivery-service/internal/publisher"
	"delivery-service/internal/router"
	"delivery-service/internal/service/deliveryserv"
	"delivery-service/internal/service/packageserv"
	"delivery-service/internal/service/shippingserv"
	"delivery-service/internal/subscribers"
	"delivery-service/pkgs/mongodb"
	"delivery-service/pkgs/rabbitclient"
	"delivery-service/pkgs/resty"
	"encoding/json"
	"github.com/ansrivas/fiberprometheus/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"log"
	"time"
)

// Injectors from server.go:

func New() (*Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	client := restyclient.InitRestyGoClient(configConfig)
	userService := userserv.NewUserService(client, configConfig)
	mongoClient, err := mongodb.OpenMongoDBConnection(configConfig)
	if err != nil {
		return nil, err
	}
	deliveryRepos := repos.NewDeliveryRepos(mongoClient)
	deliveryService := deliveryserv.NewDeliveryService(userService, deliveryRepos)
	deliveryHandle := api.NewDeliveryHandle(deliveryService)
	provinceRepository := repos.InitProvinceRepository(configConfig)
	shippingCostService := shippingserv.NewShippingCostService(provinceRepository, userService, deliveryRepos)
	shippingHandle := api.NewShippingHandle(shippingCostService)
	districtRepos := repos.InitDistrictRepository(configConfig)
	wardRepos := repos.InitWardRepository(configConfig)
	vietNamProvinceHandle := api.NewVietNamProvinceHandle(provinceRepository, districtRepos, wardRepos)
	authMiddleware := middleware.NewAuthMiddleware(userService)
	routerHandler := router.NewRouterHandler(deliveryHandle, shippingHandle, vietNamProvinceHandle, authMiddleware)
	deliveryServiceGRPCServer := deliveryGrpc.NewDeliveryServerGRPC(shippingCostService)
	connection := rabbitclient.NewRabbitClientConnection(configConfig)
	shippingPackageRepos := repos.NewShippingPackageRepos(mongoClient)
	replyPurchasePublisher := publisher.NewReplyPurchasePublisher(configConfig, connection)
	shippingPackageService := packageserv.NewShippingPackageService(deliveryRepos, shippingPackageRepos, replyPurchasePublisher)
	purchaseCreatedSub := subscribers.NewPurchaseCreatedSub(configConfig, connection, shippingPackageService)
	server := NewServer(configConfig, routerHandler, deliveryServiceGRPCServer, purchaseCreatedSub)
	return server, nil
}

// server.go:

type Server struct {
	globalCfg   *config.Config
	app         *fiber.App
	grpcServ    *grpc.Server
	purchaseSub *subscribers.PurchaseCreatedSub
}

func NewServer(
	cfg *config.Config, router2 *router.RouterHandler,
	deliServ deliveryGrpc.DeliveryServiceGRPCServer,
	purchaseSub *subscribers.PurchaseCreatedSub) *Server {

	app := fiber.New(fiber.Config{
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 5 * time.Second,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
	})

	prometheus := fiberprometheus.New("latipe-delivery-service")
	prometheus.RegisterAt(app, "/metrics")
	app.Use(prometheus.Middleware)

	app.Use(logger.New())

	app.Get("", func(ctx *fiber.Ctx) error {
		s := struct {
			Message string `json:"message"`
			Version string `json:"version"`
		}{
			Message: "delivery service was developed by TienDat",
			Version: "v1.0.1",
		}
		return ctx.JSON(s)
	})
	api2 := app.Group("/api")
	v1 := api2.Group("/v1")
	router2.
		InitRouter(&v1)

	creds, err := credentials.NewServerTLSFromFile("./server.crt", "./server.key")
	if err != nil {
		log.Fatal(err)
	}

	grpcServ := grpc.NewServer(grpc.Creds(creds), grpc.UnaryInterceptor(interceptor.MiddlewareUnaryRequest))
	deliveryGrpc.RegisterDeliveryServiceGRPCServer(grpcServ, deliServ)
	return &Server{
		globalCfg:   cfg,
		app:         app,
		purchaseSub: purchaseSub,
		grpcServ:    grpcServ,
	}
}

func (serv Server) PurchaseCreatedSub() *subscribers.PurchaseCreatedSub {
	return serv.purchaseSub
}

func (serv Server) App() *fiber.App {
	return serv.app
}

func (serv Server) Config() *config.Config {
	return serv.globalCfg
}

func (serv Server) DeliServ() *grpc.Server {
	return serv.grpcServ
}
